// Job-row helpers. The backend owns the row shape (cron.manage), so these
// functions only rely on the identity/presence fields below and treat
// everything else as unknown data that passes through untouched.
//
// Identity contract (upstream cron.manage): `job_id` is opaque technical
// identity generated by Hermes; `name` is the human-readable title. Pause,
// resume, remove and every key derived from a row use `job_id` ONLY — a
// missing or unusable id returns '' so callers fail closed instead of
// guessing identity from the display name.

import { isValidJobId } from './cronShapes';

/** One opaque backend row, as far as this plugin reads it. */
export interface RoutineJob {
  name?: unknown;
  job_id?: unknown;
  schedule?: unknown;
  disabled?: unknown;
  enabled?: unknown;
  [field: string]: unknown;
}

/** Which slice of the list the view is showing. */
export type RoutineFilter = 'all' | 'active' | 'paused';

/**
 * The list endpoint may answer with a jobs envelope or a bare array;
 * anything else normalizes to an empty list (an honest empty state, never
 * a render crash on garbage).
 */
export function normalizeJobs(payload: unknown): RoutineJob[] {
  if (Array.isArray(payload)) return payload;
  if (payload !== null && typeof payload === 'object') {
    const jobs = (payload as { jobs?: unknown }).jobs;
    if (Array.isArray(jobs)) return jobs;
  }
  return [];
}

/**
 * Canonical identity: `job_id` only, trimmed, or '' when the row carries no
 * usable one. Never falls back to `name` — a routine whose row has no id
 * is not addressable, and inventing an identity from the title is the
 * defect this contract exists to prevent.
 */
export function jobIdOf(job: unknown): string {
  const row = job as Partial<RoutineJob> | null | undefined;
  if (!row || typeof row.job_id !== 'string') return '';
  const id = row.job_id.trim();
  return isValidJobId(id) ? id : '';
}

/**
 * Canonical id inside a `cron.manage add` answer. Upstream answers
 * `{success, job_id, name, job: {...}}` and the nested row carries the same
 * `job_id`. '' when the answer carries no usable id, so a caller that still
 * needs to address the new routine fails closed instead of falling back to
 * the name it just submitted.
 */
export function jobIdFromResponse(payload: unknown): string {
  if (payload === null || typeof payload !== 'object') return '';
  const row = payload as { job_id?: unknown; job?: unknown };
  const nested =
    row.job !== null && typeof row.job === 'object'
      ? (row.job as { job_id?: unknown })
      : null;
  for (const candidate of [row.job_id, nested?.job_id]) {
    if (typeof candidate === 'string') {
      const id = candidate.trim();
      if (isValidJobId(id)) return id;
    }
  }
  return '';
}

/** A row is paused when the backend flags it disabled or un-enabled. */
export function jobPaused(job: RoutineJob | null | undefined): boolean {
  if (job?.disabled === true) return true;
  if (job?.enabled === false) return true;
  return false;
}

/** Return a copy of the row with the paused flag flipped (never mutates). */
export function withPausedFlag(job: RoutineJob, paused: boolean): RoutineJob {
  const next: RoutineJob = { ...job };
  if (paused) {
    next.disabled = true;
    if ('enabled' in next) next.enabled = false;
  } else {
    next.disabled = false;
    if ('enabled' in next) next.enabled = true;
  }
  return next;
}

/**
 * How many rows each filter would reveal (issue #79).
 *
 * Computed over whatever set the caller passes in — the page passes the
 * SEARCH-matched rows, not the whole inventory, so a chip's number is the
 * number of rows that chip would actually open. A count that ignores an
 * active search is a count the user can see is wrong.
 */
export function filterCounts(jobs: unknown): Record<RoutineFilter, number> {
  const list = Array.isArray(jobs) ? (jobs as RoutineJob[]) : [];
  const counts: Record<RoutineFilter, number> = { all: list.length, active: 0, paused: 0 };
  for (const job of list) {
    if (jobPaused(job)) counts.paused += 1;
    else counts.active += 1;
  }
  return counts;
}

/** Apply the active filter without mutating the source array. */
export function visibleJobs(jobs: unknown, filter: RoutineFilter): RoutineJob[] {
  const list = Array.isArray(jobs) ? (jobs as RoutineJob[]) : [];
  if (filter === 'active') return list.filter((job) => !jobPaused(job));
  if (filter === 'paused') return list.filter((job) => jobPaused(job));
  return list.slice();
}
