// Styles for the Routines page.
//
// Theme-first: every color reads the Desktop host variables
// (--ui-text-*, --ui-bg-*, --ui-stroke-*, --ui-accent, --ui-green,
// --ui-red) with a WCAG-measured light fallback, so the page looks native
// inside the Desktop and stays readable in isolation. No parallel design
// system: type scale, radius and status tones follow the Crew Routines
// language (compact cards, human schedule first, technical disclosure
// last). Previous hardcoded pairs measured: ink #161616 on white 18.10,
// muted #595959 on white 7.00, white on accent #0b5fff 5.13, white on
// danger #b42318 6.57, white on pine #166534 7.13.
export const ROUTINES_CSS = [
  '.hr-root{box-sizing:border-box;max-width:1040px;margin:0 auto;padding:28px 28px 40px;font-family:inherit;color:var(--ui-text-primary,#161616);background:transparent;}',
  '.hr-title{font-size:22px;line-height:1.3;margin:0 0 6px;color:var(--ui-text-primary,#161616);letter-spacing:-0.01em;}',
  '.hr-sub{margin:0 0 4px;color:var(--ui-text-tertiary,#595959);font-size:14px;line-height:1.5;max-width:72ch;}',
  '.hr-profile{display:inline-flex;align-items:center;gap:8px;margin:12px 0 0;padding:4px 10px;border:1px solid var(--ui-stroke-secondary,#d9d9d9);border-radius:999px;background:var(--ui-bg-tertiary,rgba(0,0,0,0.03));color:var(--ui-text-secondary,#404040);font-size:13px;line-height:1.5;}',
  '.hr-profile strong{font-weight:600;color:var(--ui-text-primary,#161616);overflow-wrap:anywhere;}',
  '.hr-count{margin:12px 0 0;color:var(--ui-text-tertiary,#595959);font-size:13px;}',
  '.hr-label{display:block;font-weight:600;margin:16px 0 6px;color:var(--ui-text-primary,#161616);}',
  '.hr-btn{display:inline-block;padding:8px 14px;font-size:14px;font-weight:600;color:var(--ui-text-primary,#161616);background:var(--ui-bg-elevated,#ffffff);border:1px solid var(--ui-stroke-secondary,#6e6e6e);border-radius:6px;cursor:pointer;line-height:1.3;}',
  '.hr-btn:disabled{opacity:0.55;cursor:not-allowed;}',
  '.hr-btn-small{padding:4px 10px;font-size:13px;}',
  '.hr-btn-current{outline:2px solid var(--ui-accent,#0b5fff);outline-offset:2px;}',
  '.hr-filters{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0 4px;}',
  '.hr-list{list-style:none;margin:12px 0;padding:0;display:grid;gap:10px;}',
  '.hr-card{border:1px solid var(--ui-stroke-secondary,#d9d9d9);border-radius:10px;padding:14px 16px;background:var(--ui-bg-elevated,#ffffff);}',
  '.hr-card-paused{border-left-width:4px;border-left-color:var(--ui-stroke-tertiary,#8a8a8a);background:var(--ui-bg-tertiary,rgba(0,0,0,0.02));}',
  '.hr-card-head{display:flex;gap:10px;align-items:flex-start;}',
  '.hr-card-toggle{flex:none;width:28px;height:28px;display:inline-flex;align-items:center;justify-content:center;border:1px solid transparent;border-radius:6px;background:transparent;color:var(--ui-text-tertiary,#595959);cursor:pointer;font-size:14px;}',
  '.hr-card-toggle:hover{border-color:var(--ui-stroke-secondary,#d9d9d9);color:var(--ui-text-primary,#161616);}',
  '.hr-caret{display:inline-block;transition:transform 120ms ease;}',
  '.hr-caret-open{transform:rotate(90deg);}',
  '.hr-card-title{flex:1 1 auto;min-width:0;display:flex;align-items:baseline;gap:8px;flex-wrap:wrap;}',
  '.hr-row-id{font-weight:600;font-size:15px;color:var(--ui-text-primary,#161616);overflow-wrap:anywhere;}',
  '.hr-subtitle{margin:6px 0 0 38px;color:var(--ui-text-tertiary,#595959);font-size:13px;line-height:1.5;}',
  '.hr-row-meta{color:var(--ui-text-tertiary,#595959);font-size:13px;line-height:1.5;}',
  '.hr-row-actions{flex:none;display:flex;gap:8px;flex-wrap:wrap;}',
  '.hr-badge{display:inline-flex;align-items:center;gap:6px;font-size:12px;font-weight:600;padding:2px 8px;border-radius:999px;white-space:nowrap;}',
  '.hr-badge-dot{width:7px;height:7px;border-radius:999px;background:currentColor;flex:none;}',
  '.hr-badge-active{background:color-mix(in srgb,var(--ui-green,#166534) 12%,transparent);color:var(--ui-green,#166534);border:1px solid color-mix(in srgb,var(--ui-green,#166534) 35%,transparent);}',
  '.hr-badge-paused{background:var(--ui-bg-tertiary,rgba(0,0,0,0.05));color:var(--ui-text-secondary,#404040);border:1px solid var(--ui-stroke-secondary,#6e6e6e);}',
  '.hr-badge-completed{background:color-mix(in srgb,var(--ui-green,#166534) 12%,transparent);color:var(--ui-green,#166534);border:1px solid color-mix(in srgb,var(--ui-green,#166534) 35%,transparent);}',
  '.hr-badge-error{background:color-mix(in srgb,var(--ui-red,#b42318) 10%,transparent);color:var(--ui-red,#b42318);border:1px solid color-mix(in srgb,var(--ui-red,#b42318) 40%,transparent);}',
  '.hr-details{display:grid;grid-template-columns:1fr 1fr;gap:8px 28px;margin:12px 0 0 38px;padding-top:12px;border-top:1px solid var(--ui-stroke-tertiary,#e4e4e4);}',
  '.hr-detail{display:grid;grid-template-columns:96px 1fr;gap:10px;align-items:start;}',
  '.hr-detail-label{color:var(--ui-text-tertiary,#595959);font-size:12px;line-height:1.6;text-transform:uppercase;letter-spacing:0.04em;}',
  '.hr-detail-value{color:var(--ui-text-secondary,#404040);font-size:14px;line-height:1.5;overflow-wrap:anywhere;}',
  '.hr-next{font-weight:600;color:var(--ui-text-primary,#161616);}',
  '.hr-date{color:var(--ui-text-tertiary,#595959);font-weight:400;}',
  '.hr-result{font-size:14px;line-height:1.5;}',
  '.hr-result-success{color:var(--ui-green,#166534);font-weight:600;}',
  '.hr-result-error{color:var(--ui-red,#b42318);font-weight:600;}',
  '.hr-result-neutral{color:var(--ui-text-secondary,#404040);}',
  '.hr-tech{grid-column:1 / -1;margin-top:4px;}',
  '.hr-tech-summary{cursor:pointer;color:var(--ui-text-tertiary,#595959);font-size:13px;}',
  '.hr-tech-body{display:grid;grid-template-columns:96px 1fr;gap:6px 10px;margin-top:8px;}',
  '.hr-code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:var(--ui-text-secondary,#404040);overflow-wrap:anywhere;}',
  '.hr-state{border:1px dashed var(--ui-stroke-secondary,#6e6e6e);border-radius:10px;padding:28px 20px;margin:16px 0;text-align:center;}',
  '.hr-state-title{margin:0 0 6px;font-size:15px;font-weight:600;color:var(--ui-text-primary,#161616);}',
  '.hr-state-text{margin:0;color:var(--ui-text-tertiary,#595959);font-size:14px;line-height:1.5;}',
  '.hr-spinner{display:inline-block;width:18px;height:18px;border-radius:999px;border:2px solid var(--ui-stroke-secondary,#d9d9d9);border-top-color:var(--ui-accent,#0b5fff);animation:hr-spin 0.9s linear infinite;margin-bottom:8px;}',
  '@keyframes hr-spin{to{transform:rotate(360deg);}}',
  '@media (prefers-reduced-motion:reduce){.hr-spinner{animation:none;}.hr-caret{transition:none;}}',
  '.hr-error{border:1px solid color-mix(in srgb,var(--ui-red,#b42318) 55%,transparent);border-left-width:6px;border-radius:10px;padding:14px 16px;background:var(--ui-bg-elevated,#ffffff);color:var(--ui-text-primary,#161616);margin:16px 0;}',
  '.hr-error strong{color:var(--ui-red,#b42318);}',
  '.hr-stale{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap;border:1px solid var(--ui-stroke-secondary,#d9d9d9);border-radius:10px;padding:10px 14px;margin:12px 0 0;background:var(--ui-bg-tertiary,rgba(0,0,0,0.03));color:var(--ui-text-secondary,#404040);font-size:13px;}',
  '.hr-muted{color:var(--ui-text-tertiary,#595959);font-size:14px;line-height:1.5;}',
  '.hr-status{margin-top:16px;color:var(--ui-text-tertiary,#595959);font-size:13px;}',
  '.hr-root :focus-visible{outline:2px solid var(--ui-accent,#0b5fff);outline-offset:2px;}',
  '@media (max-width:720px){.hr-root{padding:20px 16px 32px;}.hr-details{grid-template-columns:1fr;margin-left:0;}.hr-subtitle{margin-left:0;}.hr-card-head{flex-wrap:wrap;}.hr-row-actions{width:100%;}.hr-row-actions .hr-btn{flex:1 1 auto;}}',
].join('\n');
