// Styles for the Routines page.
//
// Minimalist hermes-crew aesthetic:
// Ultra-clean rows with status glyphs (green clock for active, gray pause for paused),
// icon-only actions (pause/resume/edit), clean indented subtitles and details,
// and a lateral inspector when inspecting/editing.
//
// 100% theme-adaptive with host tokens (--ui-text-*, --ui-bg-*, --ui-stroke-*,
// --dt-composer-ring, --chrome-action-hover, --ui-green, --ui-yellow, --ui-red).

export const ROUTINES_CSS = [
  '/* Base Root & Reset */',
  '.hr-root {',
  '  box-sizing: border-box;',
  '  display: flex;',
  '  flex-direction: column;',
  '  height: 100%;',
  '  min-height: 0;',
  '  min-width: 0;',
  '  margin: 0;',
  '  padding: 0;',
  '  font-family: inherit;',
  '  color: var(--ui-text-primary, var(--dt-foreground, #161616));',
  '  background: transparent;',
  '  overflow: hidden;',
  '}',
  '.hr-root *, .hr-root *::before, .hr-root *::after { box-sizing: border-box; }',
  '.hr-root :focus-visible { outline: 2px solid var(--dt-composer-ring, var(--ui-accent, #0053fd)); outline-offset: 2px; }',
  '',
  '/* Screen reader only utility */',
  '.hr-sr-only {',
  '  position: absolute;',
  '  width: 1px;',
  '  height: 1px;',
  '  padding: 0;',
  '  margin: -1px;',
  '  overflow: hidden;',
  '  clip: rect(0, 0, 0, 0);',
  '  white-space: nowrap;',
  '  border: 0;',
  '}',
  '',
  '/* Top Header Area (Minimalist) */',
  '.hr-header {',
  '  flex-shrink: 0;',
  '  padding: 4px 0 16px;',
  '  border-bottom: 1px solid var(--ui-stroke-tertiary, rgba(255, 255, 255, 0.06));',
  '  margin-bottom: 18px;',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 6px;',
  '}',
  '.hr-header-top {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  gap: 16px;',
  '}',
  '.hr-header-titles {',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 2px;',
  '}',
  '.hr-title {',
  '  font-size: 20px;',
  '  font-weight: 700;',
  '  line-height: 1.2;',
  '  margin: 0;',
  '  color: var(--ui-text-primary, #fff);',
  '  letter-spacing: -0.01em;',
  '}',
  '.hr-sub {',
  '  margin: 0;',
  '  color: var(--ui-text-tertiary, #888);',
  '  font-size: 13px;',
  '  line-height: 1.4;',
  '}',
  '.hr-profile {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 6px;',
  '  padding: 3px 10px;',
  '  border-radius: 999px;',
  '  font-size: 11px;',
  '  font-weight: 500;',
  '  background: var(--ui-bg-tertiary, rgba(255,255,255,0.04));',
  '  border: 1px solid var(--ui-stroke-tertiary, rgba(255,255,255,0.1));',
  '  color: var(--ui-text-secondary, #ccc);',
  '  margin: 0;',
  '}',
  '.hr-profile strong { font-weight: 600; color: var(--ui-text-primary, #fff); }',
  '.hr-count { margin: 0; color: var(--ui-text-tertiary, #888); font-size: 12px; }',
  '',
  '/* Controls & Toolbar (Minimalist) */',
  '.hr-toolbar {',
  '  display: flex;',
  '  align-items: flex-start;',
  '  justify-content: space-between;',
  '  gap: 16px;',
  '  margin-bottom: 14px;',
  '  flex-wrap: wrap;',
  '}',
  '.hr-search-wrap {',
  '  position: relative;',
  '  display: flex;',
  '  align-items: center;',
  '  flex: 0 1 260px;',
  '  width: 100%;',
  '  max-width: 280px;',
  '}',
  '.hr-filters-col {',
  '  display: flex;',
  '  flex-direction: column;',
  '  align-items: flex-end;',
  '  gap: 4px;',
  '  margin-left: auto;',
  '}',
  '.hr-filters {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 14px;',
  '}',
  '.hr-filter-chip {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  height: 24px;',
  '  padding: 0 2px 2px;',
  '  border: none;',
  '  border-bottom: 2px solid transparent;',
  '  background: transparent;',
  '  color: var(--ui-text-tertiary, #888);',
  '  font-size: 13px;',
  '  font-weight: 500;',
  '  cursor: pointer;',
  '  transition: all 0.15s ease;',
  '  border-radius: 0;',
  '}',
  '.hr-filter-chip:hover {',
  '  background: transparent;',
  '  color: var(--ui-text-primary, #fff);',
  '}',
  '.hr-filter-chip[aria-current="true"], .hr-filter-chip-current {',
  '  border: none;',
  '  border-bottom: 2px solid var(--dt-composer-ring, var(--ui-accent, #0053fd));',
  '  background: transparent;',
  '  color: var(--ui-text-primary, #fff);',
  '  font-weight: 600;',
  '}',
  '.hr-count-right {',
  '  font-size: 11px;',
  '  color: var(--ui-text-quaternary, #666);',
  '  text-align: right;',
  '  padding-right: 2px;',
  '  user-select: none;',
  '}',
  '.hr-search-input {',
  '  width: 100%;',
  '  height: 26px;',
  '  padding: 0 24px 0 10px;',
  '  border-radius: 6px;',
  '  font-size: 12px;',
  '  background: var(--ui-bg-card, rgba(255,255,255,0.03));',
  '  border: 1px solid var(--ui-stroke-tertiary, rgba(255,255,255,0.1));',
  '  color: var(--ui-text-primary, #fff);',
  '  outline: none;',
  '  transition: border-color 0.15s;',
  '}',
  '.hr-search-input:focus {',
  '  border-color: var(--dt-composer-ring, var(--ui-accent, #0053fd));',
  '}',
  '.hr-search-clear {',
  '  position: absolute;',
  '  right: 6px;',
  '  width: 16px;',
  '  height: 16px;',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  border: none;',
  '  background: transparent;',
  '  color: var(--ui-text-quaternary, #666);',
  '  cursor: pointer;',
  '  font-size: 10px;',
  '}',
  '.hr-search-clear:hover { color: var(--ui-text-primary, #fff); }',
  '',
  '/* Master-Detail Split Workspace */',
  '.hr-workspace {',
  '  display: flex;',
  '  flex: 1 1 0;',
  '  min-height: 0;',
  '  min-width: 0;',
  '  overflow: hidden;',
  '}',
  '.hr-feed-column {',
  '  display: flex;',
  '  flex-direction: column;',
  '  flex: 1 1 0;',
  '  min-height: 0;',
  '  min-width: 0;',
  '  overflow-y: auto;',
  '  padding: 16px 24px 32px;',
  '}',
  '.hr-feed-contained {',
  '  max-width: 860px;',
  '  margin: 0 auto;',
  '  width: 100%;',
  '}',
  '.hr-list {',
  '  list-style: none;',
  '  margin: 0;',
  '  padding: 0;',
  '  display: flex;',
  '  flex-direction: column;',
  '}',
  '',
  '/* Minimalist Row Item (Matching hermes-crew) */',
  '.hr-row {',
  '  display: flex;',
  '  flex-direction: column;',
  '  padding: 14px 6px;',
  '  border-bottom: 1px solid var(--ui-stroke-tertiary, rgba(255, 255, 255, 0.07));',
  '  transition: background 0.15s ease;',
  '  position: relative;',
  '  cursor: pointer;',
  '  background: transparent;',
  '}',
  '.hr-row:hover {',
  '  background: color-mix(in srgb, var(--chrome-action-hover, rgba(255, 255, 255, 0.04)) 40%, transparent);',
  '  border-radius: 6px;',
  '}',
  '.hr-row-top {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  gap: 12px;',
  '}',
  '.hr-row-left {',
  '  display: flex;',
  '  align-items: center;',
  '  gap: 10px;',
  '  min-width: 0;',
  '  flex: 1 1 auto;',
  '}',
  '.hr-status-indicator {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  width: 18px;',
  '  height: 18px;',
  '  flex-shrink: 0;',
  '}',
  '.hr-status-svg { flex-shrink: 0; }',
  '.hr-status-svg-active { color: var(--ui-green, #34d399); }',
  '.hr-status-svg-paused { color: var(--ui-text-tertiary, #888); }',
  '.hr-row-title {',
  '  font-size: 14px;',
  '  font-weight: 600;',
  '  color: var(--ui-text-primary, #fff);',
  '  cursor: pointer;',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '  white-space: nowrap;',
  '}',
  '.hr-row-title:hover { color: var(--ui-accent, #4a84fe); }',
  '.hr-row-actions {',
  '  display: flex;',
  '  align-items: center;',
  '  gap: 6px;',
  '  flex-shrink: 0;',
  '}',
  '',
  '/* Icon-Only Action Buttons */',
  '.hr-icon-btn {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  width: 26px;',
  '  height: 26px;',
  '  border: none;',
  '  background: transparent;',
  '  color: var(--ui-text-tertiary, #888);',
  '  border-radius: 4px;',
  '  cursor: pointer;',
  '  font-size: 0;',
  '  line-height: 0;',
  '  position: relative;',
  '  transition: all 0.15s ease;',
  '  padding: 0;',
  '}',
  '.hr-icon-btn:hover {',
  '  background: var(--chrome-action-hover, rgba(255, 255, 255, 0.08));',
  '  color: var(--ui-text-primary, #fff);',
  '}',
  '.hr-icon-btn:disabled { opacity: 0.35; cursor: not-allowed; }',
  '.hr-icon-btn::before {',
  '  content: "";',
  '  display: block;',
  '  width: 14px;',
  '  height: 14px;',
  '  background-color: currentColor;',
  '  -webkit-mask-size: contain;',
  '  mask-size: contain;',
  '  -webkit-mask-repeat: no-repeat;',
  '  mask-repeat: no-repeat;',
  '  -webkit-mask-position: center;',
  '  mask-position: center;',
  '}',
  '.hr-icon-btn-pause::before {',
  '  -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 24 24\'%3E%3Cpath fill=\'black\' d=\'M6 4h4v16H6V4zm8 0h4v16h-4V4z\'/%3E%3C/svg%3E");',
  '  mask-image: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 24 24\'%3E%3Cpath fill=\'black\' d=\'M6 4h4v16H6V4zm8 0h4v16h-4V4z\'/%3E%3C/svg%3E");',
  '}',
  '.hr-icon-btn-resume::before {',
  '  -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 24 24\'%3E%3Cpath fill=\'black\' d=\'M8 5v14l11-7z\'/%3E%3C/svg%3E");',
  '  mask-image: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 24 24\'%3E%3Cpath fill=\'black\' d=\'M8 5v14l11-7z\'/%3E%3C/svg%3E");',
  '}',
  '.hr-icon-btn-edit::before {',
  '  -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 24 24\'%3E%3Cpath fill=\'black\' d=\'M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z\'/%3E%3C/svg%3E");',
  '  mask-image: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 24 24\'%3E%3Cpath fill=\'black\' d=\'M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z\'/%3E%3C/svg%3E");',
  '}',
  '.hr-icon-btn-active { color: var(--ui-accent, #4a84fe) !important; }',
  '',
  '/* Subtitle & In-Place Details */',
  '.hr-row-sub {',
  '  margin-left: 28px;',
  '  margin-top: 3px;',
  '}',
  '.hr-row-subtitle {',
  '  font-size: 12px;',
  '  line-height: 1.4;',
  '  color: var(--ui-text-tertiary, #888);',
  '  display: flex;',
  '  align-items: center;',
  '  flex-wrap: wrap;',
  '}',
  '.hr-sub-paused { color: var(--ui-text-tertiary, #888); }',
  '.hr-sub-schedule { color: var(--ui-text-tertiary, #999); }',
  '.hr-sub-sep { margin: 0 6px; color: var(--ui-stroke-tertiary, rgba(255,255,255,0.2)); font-size: 11px; }',
  '.hr-sub-next { color: var(--ui-text-tertiary, #888); }',
  '',
  '/* Expanded In-Place Details (media_1790206808519.png) */',
  '.hr-details {',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 4px;',
  '  margin-top: 8px;',
  '  padding-top: 6px;',
  '}',
  '.hr-detail {',
  '  display: grid;',
  '  grid-template-columns: 110px 1fr;',
  '  gap: 12px;',
  '  font-size: 12px;',
  '  line-height: 1.5;',
  '  align-items: baseline;',
  '}',
  '.hr-detail-label { color: var(--ui-text-tertiary, #888); }',
  '.hr-detail-value { color: var(--ui-text-secondary, #ccc); }',
  '.hr-next { font-weight: 500; color: var(--ui-text-primary, #fff); }',
  '.hr-date { color: var(--ui-text-tertiary, #888); font-weight: 400; }',
  '.hr-result { font-size: 12px; font-weight: 500; }',
  '.hr-result-success { color: var(--ui-green, #34d399); }',
  '.hr-result-error { color: var(--ui-red, #f87171); }',
  '.hr-result-neutral { color: var(--ui-text-secondary, #ccc); }',
  '',
  '/* Lateral Inspector (Minimalist) */',
  '.hr-inspector {',
  '  display: flex;',
  '  flex-direction: column;',
  '  width: 26rem;',
  '  flex-shrink: 0;',
  '  min-height: 0;',
  '  border-left: 1px solid var(--ui-stroke-tertiary, rgba(255, 255, 255, 0.08));',
  '  background: var(--ui-bg-elevated, #161618);',
  '}',
  '.hr-inspector-header {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  gap: 10px;',
  '  padding: 14px 18px;',
  '  border-bottom: 1px solid var(--ui-stroke-tertiary, rgba(255, 255, 255, 0.06));',
  '  flex-shrink: 0;',
  '}',
  '.hr-btn-back {',
  '  border: none;',
  '  background: transparent;',
  '  color: var(--ui-text-tertiary, #888);',
  '  font-size: 12px;',
  '  cursor: pointer;',
  '  padding: 2px 4px;',
  '  border-radius: 4px;',
  '}',
  '.hr-btn-back:hover { color: var(--ui-text-primary, #fff); background: var(--chrome-action-hover, rgba(255,255,255,0.06)); }',
  '.hr-inspector-header-badges { display: flex; align-items: center; gap: 8px; }',
  '.hr-badge-subtle {',
  '  font-size: 10px;',
  '  color: var(--ui-text-tertiary, #888);',
  '  background: var(--ui-bg-quinary, rgba(255,255,255,0.05));',
  '  padding: 1px 6px;',
  '  border-radius: 4px;',
  '}',
  '.hr-inspector-body {',
  '  flex: 1 1 0;',
  '  min-height: 0;',
  '  overflow-y: auto;',
  '  padding: 18px;',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 18px;',
  '}',
  '.hr-inspector-ident { display: flex; flex-direction: column; gap: 4px; }',
  '.hr-inspector-title { font-size: 16px; font-weight: 700; margin: 0; color: var(--ui-text-primary, #fff); word-break: break-word; }',
  '.hr-inspector-id-row { display: flex; align-items: center; gap: 6px; font-size: 11px; }',
  '.hr-inspector-id-label { color: var(--ui-text-tertiary, #888); }',
  '.hr-inspector-id-code { font-family: var(--dt-font-mono, monospace); font-size: 10px; color: var(--ui-text-secondary, #ccc); background: var(--ui-bg-quinary, rgba(255,255,255,0.04)); padding: 1px 5px; border-radius: 4px; }',
  '.hr-btn-mini { padding: 1px 6px; font-size: 10px; border-radius: 4px; border: 1px solid var(--ui-stroke-tertiary, rgba(255,255,255,0.1)); background: transparent; color: var(--ui-text-tertiary, #888); cursor: pointer; }',
  '.hr-btn-mini:hover { color: var(--ui-text-primary, #fff); }',
  '.hr-inspector-section { display: flex; flex-direction: column; gap: 8px; }',
  '.hr-section-title { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: var(--ui-text-tertiary, #888); margin: 0; }',
  '.hr-kv-grid { display: grid; grid-template-columns: 86px 1fr; gap: 6px 10px; font-size: 12px; align-items: baseline; }',
  '.hr-kv-label { color: var(--ui-text-tertiary, #888); font-size: 11px; }',
  '.hr-kv-value { color: var(--ui-text-secondary, #ddd); overflow-wrap: anywhere; }',
  '.hr-kv-highlight { font-weight: 600; color: var(--ui-text-primary, #fff); }',
  '.hr-code-inline { font-family: var(--dt-font-mono, monospace); font-size: 11px; }',
  '.hr-tech-entry { display: flex; flex-direction: column; gap: 4px; }',
  '.hr-tech-entry-head { display: flex; align-items: center; justify-content: space-between; }',
  '.hr-code-block { font-family: var(--dt-font-mono, monospace); font-size: 11px; padding: 8px 10px; border-radius: 6px; background: var(--ui-bg-quinary, rgba(0,0,0,0.2)); border: 1px solid var(--ui-stroke-tertiary, rgba(255,255,255,0.06)); color: var(--ui-text-secondary, #ccc); overflow-x: auto; white-space: pre-wrap; word-break: break-all; margin: 0; }',
  '.hr-inspector-actions-section { margin-top: 6px; padding-top: 14px; border-top: 1px solid var(--ui-stroke-tertiary, rgba(255,255,255,0.06)); }',
  '.hr-inspector-actions-bar { display: flex; gap: 8px; }',
  '.hr-btn { display: inline-flex; align-items: center; justify-content: center; padding: 6px 12px; font-size: 12px; font-weight: 600; color: var(--ui-text-primary, #fff); background: var(--ui-bg-card, #222); border: 1px solid var(--ui-stroke-tertiary, rgba(255,255,255,0.12)); border-radius: 6px; cursor: pointer; transition: all 0.15s ease; }',
  '.hr-btn:hover { background: var(--chrome-action-hover, rgba(255,255,255,0.08)); }',
  '.hr-btn:disabled { opacity: 0.5; cursor: not-allowed; }',
  '.hr-btn-pause { border-color: color-mix(in srgb, var(--ui-yellow, #fbbf24) 40%, transparent); color: var(--ui-yellow, #fbbf24); background: color-mix(in srgb, var(--ui-yellow, #fbbf24) 8%, transparent); }',
  '.hr-btn-resume { border-color: color-mix(in srgb, var(--ui-green, #34d399) 40%, transparent); color: var(--ui-green, #34d399); background: color-mix(in srgb, var(--ui-green, #34d399) 8%, transparent); }',
  '',
  '/* States (Loading, Error, Empty) */',
  '.hr-state { border: 1px dashed var(--ui-stroke-tertiary, rgba(255,255,255,0.12)); border-radius: 8px; padding: 32px 20px; margin: 16px 0; text-align: center; }',
  '.hr-state-title { margin: 0 0 6px; font-size: 14px; font-weight: 600; color: var(--ui-text-primary, #fff); }',
  '.hr-state-text { margin: 0; color: var(--ui-text-tertiary, #888); font-size: 13px; line-height: 1.5; }',
  '.hr-spinner { display: inline-block; width: 20px; height: 20px; border-radius: 999px; border: 2px solid var(--ui-stroke-tertiary, rgba(255,255,255,0.2)); border-top-color: var(--dt-composer-ring, var(--ui-accent, #0053fd)); animation: hr-spin 0.8s linear infinite; margin-bottom: 10px; }',
  '@keyframes hr-spin { to { transform: rotate(360deg); } }',
  '@media (prefers-reduced-motion: reduce) { .hr-spinner { animation: none; } }',
  '.hr-error { border: 1px solid color-mix(in srgb, var(--ui-red, #f87171) 40%, transparent); border-left-width: 4px; border-radius: 8px; padding: 14px 16px; background: var(--ui-bg-elevated, rgba(255,255,255,0.02)); color: var(--ui-text-primary, #fff); margin: 16px 0; }',
  '.hr-error strong { color: var(--ui-red, #f87171); }',
  '.hr-stale { display: flex; gap: 12px; align-items: center; justify-content: space-between; flex-wrap: wrap; border: 1px solid var(--ui-stroke-tertiary, rgba(255,255,255,0.1)); border-radius: 8px; padding: 8px 12px; margin: 0 0 12px; background: var(--ui-bg-tertiary, rgba(255,255,255,0.02)); color: var(--ui-text-secondary, #ccc); font-size: 12px; }',
  '.hr-muted { color: var(--ui-text-tertiary, #888); font-size: 13px; line-height: 1.4; }',
  '.hr-status { margin-top: 10px; color: var(--ui-text-tertiary, #888); font-size: 12px; }',
  '',
  '/* Responsive adaptiveness */',
  '@media (max-width: 820px) {',
  '  .hr-workspace { flex-direction: column; }',
  '  .hr-inspector { width: 100%; border-left: none; border-top: 1px solid var(--ui-stroke-tertiary, rgba(255,255,255,0.08)); }',
  '  .hr-feed-column { padding: 12px; }',
  '}',
].join('\n');
